apiVersion: v1
kind: Service
metadata:
  name: machine-dashboard-service
  labels:
    app: machine-dashboard
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: machine-dashboard